# docker-compose.yml
services:
  postgres:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=deuna
      - POSTGRES_PASSWORD=deuna
      - POSTGRES_DB=deuna_payment_system
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres:
